### ISSUE TITLE
Policy engine for runtime-nodejs

### ISSUE THREAD

**Issue by jboulmal** [reTHINK-project/dev-runtime-core#100]
Hello,
when loading the `hyperty-runtime` into SandboxWorker  for runtime-nodejs environment.
we get the following error :
```
--- Policy Engine ---
{ msg: { id: 1 }, id: 1 }
Received message by Sandbox Worker is:(rutime-nodejs message)
 { msg: 
   { msg: 
      { type: 'create',
        from: 'hyperty-runtime://sandbox/external',
        to: 'hyperty-runtime://sandbox/internal',
        body: [Object],
        id: 1 },
     id: 2 } }
--- Policy Engine ---
{ msg: 
   { msg: 
      { type: 'create',
        from: 'hyperty-runtime://sandbox/external',
        to: 'hyperty-runtime://sandbox/internal',
        body: [Object],
        id: 1 },
     id: 2 },
  id: 2 }
```

`TypeError: Cannot read property 'split' of undefined`
   `at RuntimeCoreCtx.isToVerify (~/dev-runtime-nodejs/dist/runtime-core/src/policy/context/RuntimeCoreCtx.js:245:35)`

I believe the above message ` {msg :.....` is not well formatted ( `message.from`  ) in [RuntimeCoreCtx.js](https://github.com/reTHINK-project/dev-runtime-core/blob/develop/src/policy/context/RuntimeCoreCtx.js#L222).

**Comment by pchainho** [comment]
somewhere in the sandbox implementation you are adding the message Object inside another message object. And this message is between a minibus external to the sandbox and internal minibus internal do the mini bus. It shouldn't go through the policy engine which only intercepts messages in the msg bus.

why are you adding the runtime core inside a sandbox? I suspect this is the main reason for the problem...

**Comment by jboulmal** [comment]
well I have to investigate that more. It mainly happens when we deploy [RuntimeUA.js#L470](https://github.com/reTHINK-project/dev-runtime-core/blob/master/src/runtime/RuntimeUA.js#L470), in 
`return _stubSandbox.deployComponent(_stubSourcePackage.sourceCode, runtimeProtoStubURL, configuration);` and of course inside a Sandbox.

**Comment by jboulmal** [comment]
I have corrected the message Object exchanged between `SandboxWorker` and `ContextServiceProvider`.

However, I still get two error messages:
``` 
1- TypeError: Cannot read property 'split' of undefined
    at RuntimeCoreCtx.isToVerify (/home/jamal/Desktop/Test_Remote_Proto/dev-runtime-nodejs/dist/runtime-core/src/policy/context/RuntimeCoreCtx.js:245:35)

```
and 
```
2---- Policy Engine ---
{ type: 'read',
  from: 'runtime://hybroker.rethink.ptinovacao.pt:8080/5821/registry/',
  to: 'domain://registry.sandbox/',
  body: 
   { resource: 'hyperty-runtime://sandbox/external',
     search: 'dataObjectPerURL' },
  id: 2 }
resolve domain://registry.sandbox/
Resolved:  msg-node.sandbox/protostub/920

Something failed on the deploy of protocolstub:  Response timeout!
Failed to deploy the ProtocolStub component  Response timeout!
no identity was found
PIPELINE-ERROR:  "no identity was found"

Something failed on the deploy of protocolstub:  Response timeout!
Failed to deploy the ProtocolStub component  Response timeout!
no identity was found
PIPELINE-ERROR:  "no identity was found" 
```
Ìn order to reproduce these errors yourself, rendez-vous on `nodejs-remote-protostub` branch on [dev-runtime-nodejs](https://github.com/reTHINK-project/dev-runtime-nodejs/tree/nodejs-remote-protostub)
Thanks for your feedback!

**Comment by AnaSLCaldeira** [comment]
Jamal, I just corrected the code that triggered the errors you got to the 'develop' branch. Let me know if the problem persists!

**Comment by jboulmal** [comment]
Hi,
I have took some time to try it, we still get the error :
``` TypeError: Cannot read property 'split' of undefined
    at RuntimeCoreCtx.isToVerify (/home/jamal/Desktop/Test_Remote_Proto/dev-runtime-nodejs/dist/runtime-core/src/policy/context/RuntimeCoreCtx.js:245:35)```

I invite you to check on `nodejs-remote-protostub` branch on [dev-runtime-nodejs](https://github.com/reTHINK-project/dev-runtime-nodejs/tree/nodejs-remote-protostub), I suspect problems coming from the messages (formats) exchanged ? not the 'split' ?

**Comment by jboulmal** [comment]
It's working now!. I no more have errors on that 'split'. However, I still have `--policy engine--` `create` that repeats.
 ```
--- Policy Engine ---
{ type: 'create',
  from: 'runtime://hybroker.rethink.ptinovacao.pt:8080/1474/registry/',
  to: 'domain://msg-node.hybroker.rethink.ptinovacao.pt/hyperty-address-allocation',
  body: { value: { number: 1 } },
  id: 1 }
resolve domain://msg-node.hybroker.rethink.ptinovacao.pt/hyperty-address-allocation
Resolved:  msg-node.hybroker.rethink.ptinovacao.pt/protostub/5951
--------------------------- Inside ContextServiceProvider : Received message is :----------------------------:
  { type: 'create',
  from: 'runtime://hybroker.rethink.ptinovacao.pt:8080/1474/registry/',
  to: 'domain://msg-node.hybroker.rethink.ptinovacao.pt/hyperty-address-allocation',
  body: { value: { number: 1 } },
  id: 1 }

```
Thanks

**Comment by AnaSLCaldeira** [comment]
Jamal, are you referring to the code you showed in your answer? Isn't it the same message being printed both at the Policy Engine and ContextServiceProvider classes?

**Comment by jboulmal** [comment]
Yes, is the same!
![screenshot from 2016-07-25 17 14 03](https://cloud.githubusercontent.com/assets/15377466/17106333/37b3acc0-528b-11e6-8c8c-f508a183a32b.png)

**Comment by AnaSLCaldeira** [comment]
Ok, good. Are you having any more trouble with the Policy Engine?

**Comment by jboulmal** [comment]
Except that repeating message that I don't understand ? Everything is fine with Policy engine for now !
Thanks for the help!
