### ISSUE TITLE
Please move catalogue descriptor URL adaption into RuntimeUA and merge dev-service-framework:revised-catalogue into dev-service-framework:develop

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-runtime-core#101]
Currently, [RuntimeCatalogue has descriptor url adaptions like this](https://github.com/reTHINK-project/dev-service-framework/blob/master/src/runtime-catalogue/RuntimeCatalogue.js#L82):
```
let dividedURL = divideURL(stubURL);
let type = dividedURL.type;
let domain = dividedURL.domain;
let protostub = dividedURL.identity;

if (!protostub) {
  protostub = 'default';
} else {
  protostub = protostub.substring(protostub.lastIndexOf('/') + 1);
}

let prefix = 'catalogue.'
if (stubURL.includes('catalogue')) {
  prefix = '';
}

stubURL = type + '://' + prefix  + domain + '/.well-known/protocolstub/' + protostub;
```
Code like this was removed from the [revised RuntimeCatalogue implementation](https://github.com/reTHINK-project/dev-service-framework/blob/revised-catalogue/src/runtime-catalogue/RuntimeCatalogue.js) and should be moved into RuntimeUA instead.

Please move the generation/adaption of descriptor URLs into the RuntimeUA, and merge the revised RuntimeCatalogue into the develop or master branch of dev-service-framework, since it also contains the fix for https://github.com/reTHINK-project/dev-service-framework/issues/50

**Comment by pchainho** [comment]
This is part of the interaction logic with the Back-end Catalogue servers and should be performed by the RuntimeCatalogue not by the RuntimeUA

**Comment by Endebert** [comment]
I disagree. The adaptions described are not part of the interaction logic with the Back-end Catalogue servers, they are about the URL the interaction logic is based on. If no proper URL is provided to the RuntimeCatalogue, it can't be expected of the catalogue to do some black magic to get it working somehow.

Examples:

* The adaptions above prefix the domain name with "catalogue.", which is specific to the test/deployment environment. Arguably, this should not be hard coded this way at all, and be configurable instead.
* The adaptions above create a resource path if only the domain was provided. Obviously, the RuntimeCatalogue expects a URL with a valid resource path to work with, and the RuntimeUA should provide it. The RuntimeCatalogue should not be expected to "guess" the correct resource path.

That is why I believe the adaptions should be made by the RuntimeUA. The RuntimeUA should make sure it provides with RuntimeCatalogue with a working URL that contains a proper resource path, and then the RuntimeCatalogue returns an instance of the requested resource.

**Comment by pchainho** [comment]
done
