### ISSUE TITLE
Oauth url invalid

### ISSUE THREAD

**Issue by dvilchez** [reTHINK-project/dev-runtime-core#102]
With last version of runtime google returns 

`
{
  "error": "invalid_request",
  "error_description": "Missing required parameter: code"
}
`
after request for authentication
https://www.googleapis.com/oauth2/v4/token?code=&client_id=808329566012-tqr8qoh111942gd2kg007t0s8f277roi.apps.googleusercontent.com&client_secret=Xx4rKucb5ZYTaXlcZX9HLfZW&redirect_uri=https://hybroker.rethink.ptinovacao.pt&grant_type=authorization_code

**Comment by vitormsilva** [comment]
Hi @dvilchez, this issue can be closed?
