### ISSUE TITLE
No Identity was Found

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#104]
This error occurs using the Connector hyperty, when a Delete message is received by the Syncher (onRemoteDelete) ie when receiving a request to close the connection from the remote peer

I suspect the "deleteMsg.body.identity" is missing and thus this bug would come from the Id Module or from the Policy Engine.

**Comment by AnaSLCaldeira** [comment]
@pchainho, I just corrected the error, thanks for detecting it.
