### ISSUE TITLE
Interworking with Legacy Services

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#107]
This issue is to discuss the impact in the Core Framework of the support of interworking with Legacy Services and it should be aligned with the results of T6.3.

Some initial ideas on an Interworking  architecture fully supported by the Runtime with Inteworking Protostubs (IWStub) and Interworking Hyperties are depicted in the picture below:

https://drive.google.com/file/d/0BxId0_H_1nc4RDBiZEtGS09yTU0/view?usp=sharing

It considers the possibility that the protocol used by the Legacy Domain also includes some Id Management features mainly authentication. Thus, the IWStub would also incorporate IdpProxy features.

The deployment of the IWHyperty and associated IWStub can be triggered by the discovery service when the User URL is not supported by a reTHINK domain but by a legacy domain.

**Comment by antonroman** [comment]
Hi, 

I was considering of the IWStub approach, and it could work but not from a browser (which only can send HTTPS and WSS traffic). It would be feasible from the Node runtime, for example a IWSTub to interact with a SIP endpoint. 
Do I develop the idea? Maybe the easier approach would a special type of runtime, which can interact with reTHINK for one side and which speaks other protocol on the other side, the same way is done with SIP-H323, SIP-ISDN, etc.

**Comment by pchainho** [comment]
@antonroman you are right for protocols not supported by the Browser. But we can also interoperate with legacy services using HTTPS / WSS protocols eg with Slack, and for these ones we could avoid having a Gateway.

Regarding "Runtime GWs" what special features would be needed? Probably, having there IWHyperties that would be registered in a domain registry would enable dynamic discovery of GWs for associated Legacy Services.

**Comment by pchainho** [comment]
Pls provide these specs [here](https://github.com/reTHINK-project/specs/blob/master/legacy-interworking/readme.md)

**Comment by pchainho** [comment]
this is duplicated with https://github.com/reTHINK-project/specs/issues/4.
