### ISSUE TITLE
Improve the way how we distribute the runtime-core

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-runtime-core#110]
Due an issue with nodejs, we will change the way how the distribution files are made. 
This will be done because they can't load or had errors loading modules from runtime-core and service-framework.

**Before:**
  - transpile the code from ES6 to ES5 and
  - with the browserify we did a bundle with all related modules and inheritances;

**Now on #develop-improves branches**
  - transpile the code from ES6 to ES5

With this probably we can fix other issues, like:
 - #91 - Uglify leads to error when calling generateGUID() in runtime-browser

**NOTE**
The browserify will work to generate a Runtime User Agent dist, because it needed to be a bundle, but now we will have an [BrowserRuntime.js](https://github.com/reTHINK-project/dev-runtime-core/blob/develop-improves/dist/Runtime.js) for browser and other for [NodeRuntime.js](https://github.com/reTHINK-project/dev-runtime-core/blob/develop-improves/dist/NodeRuntime.js)

I would like to listen to other opinions and suggestion.

This issue is related with service-framework issue [#56](https://github.com/reTHINK-project/dev-service-framework/issues/56)

**Comment by jboulmal** [comment]
Hi,
We understood the idea of bundle files in case of browser web workers. Where we cannot use `require` to load in any code.  But different environments have different requirements. Indeed, in NodeJS the normal way of doing things is to use `require` to load libraries.
Today, in `#develop-improves` branch in `#runtime-nodejs`, we only  transpile the code from ES6 to ES5, but this is not a bundle file. Thus, we need to `require` node_modules. Another solution would be to find a way to create standalone files specific  for NodeJS.

**Comment by NicoApizee** [comment]
One happy day, the transpilation step will be no more necessary (http://node.green). Meanwhile, it suppose to use babel process but it don't seem to be able to bundle files & deps.

Code inclusion via a require, or es6 import remain the only "natural way" in node.js. That implies using native npm tools & package.json to manage external dependencies (with versioning, environment).

**This problem not only concern the runtime-core or service-framework, but all libs used in runtime / protostub / hyperty...**
Considering this, the catalogue mechanism is not usable (or appear very impractical) for nodejs environnement.

In case of the nodejs protostub for example, we include dep socket.io-client (which is usable on node, and browser compatible with browserify/webpack/...).
So the bundle will work fine on browser, but we must install it then use it as requirement on node.

Btw I imagine that a specific build of vertx & matrix protostub must be done for node to support websocket ?

**Comment by vitormsilva** [comment]
Hi,

@jboulmal, the browserify should support the nodejs bundle. In the "dist" folder of "develop-improves" branch you can find all files to be distributed for the runtime-node or runtime-browser, an there you could use the browserify to make a bundle if is needed, like the runtime-browser does. Currently you can find there one for the browser (runtime.js) and another for the node (NodeRuntime)


@NicoApizee,
> This problem not only concern the runtime-core or service-framework, but all libs used in runtime / protostub / hyperty...
Protostub: yes.. we should have 2 versions of protostubs that use web sockets
Runtime: for runtime we just create a version for nodejs and another to browser
Hyperties: it should be possible to have hyperties that work on nodejs and browser and others that are constrained to browsers or nodejs; The hyperty descriptor has a "constrains" field that defines capabilities required from the runtime. Based on this field we should decide which version to be used if available.

> Considering this, the catalogue mechanism is not usable (or appear very impractical) for nodejs environnement.

Why? in the future exists one property in hyperties, runtime and protostub who define the runtimeType, the RuntimeHypertyCapabilities and RuntimeProtostubCapabilities, as you can see [here](https://github.com/reTHINK-project/dev-service-framework/tree/master/docs/datamodel/core/hyperty-catalogue)

> In case of the nodejs protostub for example, we include dep socket.io-client (which is usable on node, and browser compatible with browserify/webpack/...) so the bundle will work fine on browser.
>But we must install it for node:
npm install socket.io-client
then use it as requirement on node:
var io = require('socket.io-client');
babel will keep this code as it (or convert es6 import to native require).

I don't know, I don't test yet nodejs protostub on browser and node.

> Btw I imagine that a specific build of vertx & matrix protostub must be done for node to support websocket ?
reTHINK-project/dev-msg-node-vertx#20

yes, i think so.

**Comment by NicoApizee** [comment]
Even if can catalogue is able to serve code depending of environment, we must find a nicely way to bundle libs and all dependencies.
We have tried with nodejs protostub with standalone & node options of browserify, but without success.

@vitormsilva from the vertx protostub that work on runtime-nodejs we see a require('ws') which give websocket support in node, but it seem not bundle with the protostub. It means that somewhere else the module has been include in node_module dependencies.

**Comment by dvilchez** [comment]
Hi @vitormsilva, @NicoApizee, @jboulmal 

I don't think there is a real alternative to use bundle files on node runtime, as you said before is not only runtime core, runtime-node should be able to load hyperties, protostubs and any component distributed by the catalogue. Although it is not a common practice it should work.

The other issue is to generate specific files for each distribution, this is a real pain and at the end of the day very prone to errors.

I guess we have to work on to build isomorphic/universal components and one distribution file compatible with both environments.

**Comment by vitormsilva** [comment]
Hi, 

We did some improves on dev-service-framework, runtime-core, and nodejs-runtime, all in the develop-improve branches;

**service-framework:**
 - we did changes to the PersistenceManager - because the problem was that (imo, if we use the factory to set the Sandbox, the 'Requests' why not use the same to set the localstorage)
 - we did changes to the RuntimeCatalogue to support the new way of PersistenceManager is used;
 - generate a bundles of modules, like we did before, with the browserify and `--standalone` option

**runtime-core:**
 - we did changes to the modules who using the Persistence Manager to handle with it;
 - generate a bundle of modules, like before, with the browserify and `--standalone` option

**runtime-nodejs:**
 - we added to the **RuntimeFactory** the module *node-localstorage* and instaciate the PersistenceManager;
```javascript
    import { LocalStorage } from 'node-localstorage';
    //...
    persistenceManager() {

      let localStorage = new LocalStorage('./scratch');
      return new PersistenceManager(localStorage);
    },
    //...
```

This changes worked.. as you can see on screenshot

![screenshot from 2016-08-25 17-02-26](https://cloud.githubusercontent.com/assets/10596749/17976834/10213668-6ae7-11e6-9d3a-fc3ab2f0f314.png)

We can sent a message from browser toolkit to the nodejs-runtime;

@dvilchez, sorry for change your code.
You will need update your RuntimeFactory with some code like this:
```javascript
 //....
  persistenceManager() {

    let localStorage = window.localStorage;
    return new PersistenceManager(localStorage);
  },
 //....
```

**Comment by dvilchez** [comment]
@vitormsilva 
> we did changes to the PersistenceManager - because the problem was that 
I disagree, in a more general sense the problem is generate a bundle file containing an isomorphic library for both environments. I succeeded in this task before without modify any code.

>(imo, if we use the factory to set the Sandbox, the 'Requests' why not use the same to set the localstorage)
Neither in my opinion  but, since this solution doesn't address the whole problem is only another patch on top of a bunch of patchs.

>@dvilchez, sorry for change your code.

Feel free, it is our code.

Only to be clear on this, I don't agree with this "solution"

**Comment by vitormsilva** [comment]
> I disagree, in a more general sense the problem is generate a bundle file containing an isomorphic library for both environments. I succeeded in this task before without modify any code.

Go ahead and generate the file without modify the code, and let me know how you did, because, as I said before, i could doing something wrong;

> Neither in my opinion but, since this solution doesn't address the whole problem is only another patch on top of a bunch of patchs.

Why you say this? what kind of patchs you are talking about?

> Only to be clear on this, I don't agree with this "solution" because it is only a temporary short range patch.

why is a short range patch?

**Comment by dvilchez** [comment]
@vitormsilva I did it, https://github.com/reTHINK-project/dev-runtime-core/issues/95 and in slack (unfortunately we got over free slack limits and I can't link you to the conversation)

**Comment by dvilchez** [comment]
@vitormsilva How do you want to proceed with needed changes in runtime-browser? In a separated branch or wait until a new version of runtime-core/service-framework implements these changes...

**Comment by vitormsilva** [comment]
Hi @dvilchez, IMO, on a separate branch, so that we can test.

**Comment by pchainho** [comment]
I understand an agreement was reached and already implemented. Reopen pls if I'm wrong
