### ISSUE TITLE
"keep-alive" messages not according to spec

### ISSUE THREAD

**Issue by nunofmn** [reTHINK-project/dev-runtime-core#117]
Keep-alive messages sent by the runtime to the domain registry are not according to the spec:
https://github.com/reTHINK-project/dev-registry-domain/issues/28

The keep-alive message sent to the RegistryConnector/Domain-Registry does not contain the resource field as is described in the spec. Instead, of the full hyperty fields it should only include the resource field: the URL of the resource to be kept alive.

**Comment by pchainho** [comment]
I understand this has been fixed. @gamdias pls reopen if needed

**Comment by nunofmn** [comment]
Is this fixed @gamdias? Just to be sure, before releasing the new registry-connector version.
