### ISSUE TITLE
Runtime Registry: Reusage of addresses support

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#121]
[Reusage of Hyperty and Data Object URLs](https://github.com/reTHINK-project/specs/issues/6)

**Comment by gamdias** [comment]
I have been working on the reusage of Hyperty and Data Objects, as well as the persistence of those URL's. I will updated the status when the work is commited.

**Comment by gamdias** [comment]
implemented the re-usage and persistence of the Hyperty and Data Object addresses in runtime registry. 

the changes can be seen in this branch: https://github.com/reTHINK-project/dev-runtime-core/tree/dev-address-reusage

if there is any problem with the implementation, please reopen the issue.
