### ISSUE TITLE
Policy Engine: replace persistence-manager by storage-manager

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#125]
As agreed [here](https://github.com/reTHINK-project/dev-runtime-core/issues/119)

New release is pending on this one.

**Comment by gamdias** [comment]
replaced the persistence manager to the storage manager in policy engine.
the changes can be seen in this branch: https://github.com/reTHINK-project/dev-runtime-core/tree/dev-address-reusage

if there is any problem with the implementation, please reopen the issue.
