### ISSUE TITLE
Tests not working after merging with 'develop' branch

### ISSUE THREAD

**Issue by ishantiw** [reTHINK-project/dev-runtime-core#130]
After merging the changes from develop branch to develop-GraphConnector branch, When I'm trying to run tests for GraphConnector.spec.js, it is throwing below error.

![image](https://cloud.githubusercontent.com/assets/9600691/19896549/08a4884c-a055-11e6-9c6e-07a21fb396f8.png)
Before merging with 'develop' branch the tests were working

**Comment by ishantiw** [comment]
Note: I did following changes in `Karma.config.js` file.
![image](https://cloud.githubusercontent.com/assets/9600691/19897414/3cf19e02-a058-11e6-8421-98bb0ff38c33.png)

**Comment by vitormsilva** [comment]
For me you could have some problems:

1. Your package.json is outdated [develop](https://github.com/reTHINK-project/dev-runtime-core/blob/develop/package.json) version vs [develop-graphConnector](https://github.com/reTHINK-project/dev-runtime-core/blob/develop-graphConnector/package.json)
2. you could not pointing to the right dev-service-framework branch, you should use develop.
3. when you merge you, if you have conflicts, that conflicts could be not right resolved.

For my side the test run perfectly as you can see on printscreens;
![screenshot from 2016-11-02 10-06-27](https://cloud.githubusercontent.com/assets/10596749/19924578/6dc3aa70-a0e4-11e6-829d-0d0f5cff18a3.png)
![screenshot from 2016-11-02 10-08-14](https://cloud.githubusercontent.com/assets/10596749/19924579/6dc54bd2-a0e4-11e6-8c79-3806df36f8cb.png)

I only did, npm update in your branch.. and run karma tests

**Comment by ishantiw** [comment]
After struggling with all the re-installation and npm updates, I upgraded my nodejs version and it works now thanks @vitormsilva . I will close this issue now.
