### ISSUE TITLE
Runtime Registry: P2P Protostubs support

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#134]
- [x] [Hyperty deployment extension for P2P connections](https://github.com/reTHINK-project/specs/blob/master/dynamic-view/basics/deploy-hyperty.md)
- [x] [Hyperty and Data object Registry model extension for P2P connections](https://github.com/reTHINK-project/specs/tree/master/datamodel/core/hyperty-registry)
- [x] [Address Resolution extension for P2P connections](https://github.com/reTHINK-project/specs/blob/master/dynamic-view/basics/resolve-routing-address.md)
- [x] [Hyperty Discovery extension for P2P connections](https://github.com/reTHINK-project/specs/blob/master/dynamic-view/discovery/hyperty-discovery.md)

**Comment by vitormsilva** [comment]
Hi, 
I have a problem with the P2P resolve. 
When a hyperty is registred, and the messages will be send to other hyperty, i always have `checkHypertyP2PHandler don't find any hyperty`.

![screenshot from 2016-12-06 17-15-59](https://cloud.githubusercontent.com/assets/10596749/20962754/8d6a3710-bc62-11e6-901a-e7f07cd099dc.png)

Could you check the registerHyperty and from step 6 to step 22 [here](https://github.com/reTHINK-project/specs/blob/master/dynamic-view/basics/resolve-routing-address.md).

If you need help, we can try to help you..

**Comment by vitormsilva** [comment]
I found other problem.. I don't know if it's related to, but seems have some "fake" data, in these case to register dataObjects.

![screenshot from 2016-12-07 12-19-24](https://cloud.githubusercontent.com/assets/10596749/20967739/ed5eee48-bc78-11e6-85ce-7c6315807650.png)

**Comment by tiagolb** [comment]
That error message comes from a reject in the checkHypertyP2pHandler function which is responsible for searching in the local cache for a p2phandler and if no p2phandler is foound it should trigger a discovery process (step 9 to step 14 of the spec).

But this discovery process is not yet done. I'm looking into it.

**Comment by tiagolb** [comment]
@BernardoMG The function to be modified in order to support the discovery service for finding the p2pHandler is called checkHypertyP2pHandler in line 800 of the Registry.js. There's a TODO comment in that line where the discovery process must be triggered.

**Comment by BernardoMG** [comment]
@tiagolb Currently I'm working on some issues on Domain Registry, i will see that as soon as I can.

**Comment by BernardoMG** [comment]
@vitormsilva @tiagolb Already implemented the discovery process in checkHypertyP2PHandler. The changes are in `dev-p2p`branch.

**Comment by pchainho** [comment]
pls in case they are complete, update the the tasks list above and close the issue if everything is done. Otherwise comment here what is missing

**Comment by pchainho** [comment]
Done
