### ISSUE TITLE
Catalog uris resolution

### ISSUE THREAD

**Issue by dvilchez** [reTHINK-project/dev-runtime-core#156]
It doesn't work with subdomains for legacy interworking.

<img width="871" alt="screen-shot-2017-02-07-10-41-52" src="https://cloud.githubusercontent.com/assets/153025/22685811/0dd01a06-ed22-11e6-97c9-f1afa764c47b.png">

Right domain: ims.rethink-project.eu

**Comment by pchainho** [comment]
It is working. Try in dev-p2p, pls

![image](https://cloud.githubusercontent.com/assets/3893553/22706679/0aa459a0-ed68-11e6-989b-e0dd9743deaf.png)

**Comment by pchainho** [comment]
reopen if needed pls
