### ISSUE TITLE
IDM and IdP Proxy: assertions  are not validated by the recipient runtime

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#158]
As fas as I understand, the IDM and IdP Proxies are not yet validating assertions generated by the source runtime

**Comment by tiagolb** [comment]
The IDM is requesting this validation to the IdP Proxy. We can see this in the code here:

![issue158](https://cloud.githubusercontent.com/assets/8178030/23025377/ac65a700-f455-11e6-8647-134dcf88f153.png)

And we can also see that this request is being made here:

![issue158-2](https://cloud.githubusercontent.com/assets/8178030/23025426/daa29d44-f455-11e6-9154-54f3e4438be5.png)

Now, I'm verifying that the `validateAssertion` method is correctly implemented in the IdP Proxies.
