### ISSUE TITLE
Id Token expiry time validation

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#163]
Currently, IDM re-uses Id Tokens and Access Tokens without checking the expiry time.

**Comment by tiagolb** [comment]
@pchainho I have fixed this issue in this [branch](https://github.com/reTHINK-project/dev-runtime-core/tree/issue163).

But for legacy hyperties the assertion does not have an expiration time for the access token. So I wont close this issue yet.

**Comment by dvilchez** [comment]
But I am using Google to get the token and it has an expiration time. @pchainho @tiagolb

**Comment by tiagolb** [comment]
@dvilchez I don't understand why this issue was reopened. As I mentioned before, this issue has been fixed [here](https://github.com/reTHINK-project/dev-runtime-core/tree/issue163). Please explain clearly any subjacent issue that may concern you regarding this.

**Comment by dvilchez** [comment]
Hi @tiagolb, probably I misunderstanding you I thought you didn't implement expiration date verification for legacy domains.

Could you confirm it is now working? @tiagolb

**Comment by tiagolb** [comment]
I didn't implement expiration time verification for the Slack.com domain because it does not have any expiration time. I left a link on the closing comment for this issue confirming this. For the remaining domains this is implemented.

**Comment by pchainho** [comment]
I guess in some legacy domains like IMS, you may still have tokens with expiration date

**Comment by tiagolb** [comment]
I think the solution must be to offload the token expiration verification to the IdP Proxy then, and the IDM sends a message to the corresponding IdP Proxy querying if the token is valid or not. For domains that send tokens that are always valid they just need to return `true`.

**Comment by tiagolb** [comment]
I have fixed this issue by verifying for all identities (even for legacy domains) whether the identity assertions has the expiration time. If it does not, then I assume the token does not expire, otherwise I test it accordingly.

I'll create a document specifying how the IdP Proxy must add the expiration time to the identity assertion on the `generateAssertion` function.
