### ISSUE TITLE
karma Test is not working for the graphConnector

### ISSUE THREAD

**Issue by SenanSharhan** [reTHINK-project/dev-runtime-core#170]
We have merged our branch " develop-graphConnector " with the develop branch, and every thing is working except the karma test is not calling any tests of the (test/GraphConnector.spec.js) !

The test results can be seen here 
https://travis-ci.org/reTHINK-project/dev-runtime-core/builds/209015804

and this is our tests 
https://github.com/reTHINK-project/dev-runtime-core/blob/develop-graphConnector/test/GraphConnector.spec.js

@fbeierle

**Comment by vitormsilva** [comment]
Hi,
I was looking at this issue.. and in my opinion, you should change your testing code from:

```javascript
let identityModule = {
  getIdentities: () => {
    let identities = [];
    let identityBundle = {identity: 'user://gmail.com/openidtest10', token: 'idToken'};
    identities.push(identityBundle);
    return identities;
  }
};

let getRegistry = new Promise(function(resolve, reject) {
  let registry = new Registry(runtimeURL, appSandbox, identityModule);
  resolve(registry);
});

getRegistry.then(function(registry) {
    describe('Graph Connector', function() {
```
to something like this:

```javascript
describe('Graph Connector', function() {
   // this will set this like a global variables
   let identityModule;
   let registry;

   // this will be executed before all the tests, and you can garantee this will be setted
   before(function() {
      identityModule = {
        getIdentities: () => {
          let identities = [];
          let identityBundle = {identity: 'user://gmail.com/openidtest10', token: 'idToken'};
          identities.push(identityBundle);
          return identities;
       }
     }

     // instanciate the registry;
     registry = new Registry(runtimeURL, appSandbox, identityModule);
};
```

Probably you will have more errors when fixing this.

You can "mock" the registry and other modules like you did to the `identityModule`, in this snippet, to handle only the methods what you want.

You can look at other tests.

Try and let me know if it is works;

**Comment by SenanSharhan** [comment]
@vitormsilva  

i did what you what you suggested, but still the same !

the code
https://github.com/reTHINK-project/dev-runtime-core/blob/7be5c01113d17efb623179ba49a17f98206340fe/test/GraphConnector.spec.js#L27

the test result ! 
https://travis-ci.org/reTHINK-project/dev-runtime-core/builds/211430292

**Comment by vitormsilva** [comment]
My mistake, sorry, I forgot close the `before` function with `(` at the end.

```javascript

   // this will be executed before all the tests, and you can garantee this will be setted
   before(function() {

      identityModule = {
        getIdentities: () => {
          let identities = [];
          let identityBundle = {identity: 'user://gmail.com/openidtest10', token: 'idToken'};
          identities.push(identityBundle);
          return identities;
       }
     }

     // instanciate the registry;
     registry = new Registry(runtimeURL, appSandbox, identityModule);
  }
```
You should not only copy and paste but try to understand how it's done.

**Comment by SenanSharhan** [comment]
@vitormsilva  i already did close the `before` function with **`)`**, but the problem was i closed it at the end of the code. 

The code looks like this now :

```
    before(function () {

        let identityModule = {
            getIdentities: () => {
                let identities = [];
                let identityBundle = {identity: 'user://gmail.com/openidtest10', token: 'idToken'};
                identities.push(identityBundle);
                return identities;
            }
        };

        // instanciate the registry;

        registry = new Registry(runtimeURL, appSandbox, identityModule, runtimeCatalogue, runtimeCapabilities, storageManager);
        msgbus = new MessageBus(registry);
        registry.messageBus = msgbus;
    });
```

but i get now another error `"The address allocation was not instaniated"` see here ->
https://travis-ci.org/reTHINK-project/dev-runtime-core/builds/211721321#L2018

**Comment by vitormsilva** [comment]
Instantiate the Address Allocation module like this:

```javascript

// Imports
import AddressAllocation from '../src/allocation/AddressAllocation';

// code inside the "before" function
      registry = new Registry(runtimeURL, appSandbox, identityModule, runtimeCatalogue, runtimeCapabilities, storageManager);
      msgbus = new MessageBus(registry);

      new AddressAllocation(runtimeURL, msgbus, registry);

      registry.messageBus = msgbus;
// ....
```

**Comment by vitormsilva** [comment]
@SenanSharhan,

Have you progressed on this? need some kind of help?

**Comment by SenanSharhan** [comment]
@vitormsilva, 

Thanks, now everything is working fine, see (https://travis-ci.org/reTHINK-project/dev-runtime-core/builds/213385758).
