### ISSUE TITLE
Supporting the openPopup function in the hyperty-toolkit

### ISSUE THREAD

**Issue by tiagolb** [reTHINK-project/dev-runtime-core#177]
Acording to issue #171 , the "window" reference needs to be removed from the IDM.

As I mentioned in issue #171 the `openPopup` funtion where this reference is present has been moved to the identity-gui in `dev-runtime-browser`. But, since this function is needed when the toolkit is in `dev` mode, as well as in `browser` mode, I can't just have it in the dev-runtime-browser alone.

@vitormsilva Mentioned that this function needs to be supported by the hyperty-toolkit via msg-bus (probably in the `resources/factories/rethink.js` file).

**Comment by vitormsilva** [comment]
What you need from my side? How can i help you?

**Comment by tiagolb** [comment]
@vitormsilva If you could implement the openPopup function in the hyperty-toolkit that would be great. I'm having some trouble doing so and since you know how the hyperty works (unlike me) you can do that much faster.

The openPopup function is [here](https://github.com/reTHINK-project/dev-runtime-core/blob/develop/src/identity/IdentityModule.js#L441).

**Comment by Ricardo-Chaves** [comment]
This must be implemented at the runtime. It is not a IdM issue. Correct @vitormsilva / @pchainho?

**Comment by vitormsilva** [comment]
I did a version of the toolkit with the `openPopup` feature.
By default only load the `google.com` IDP.

It's in develop branch of the toolkit.

**Comment by tiagolb** [comment]
@vitormsilva I'll test it tomorrow and once everything works we can close this issue as well as issue #171

**Comment by tiagolb** [comment]
I've modified the code [here](https://github.com/reTHINK-project/dev-hyperty-toolkit/pull/42) to support just the openPopup function, which is what we need. I'll now close this issue.
