### ISSUE TITLE
Login with others IDP

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-runtime-core#207]
Hi @tiagolb,

We are testing the login with other IDPs, like Microsoft, and for every IDP we chose, the login popup which is opening is always the google one.
I have some print screens to help understand:

![screenshot from 2017-06-08 10-15-54](https://user-images.githubusercontent.com/10596749/26921350-aeefbe1c-4c33-11e7-8327-1932b6475381.png)

**Comment by tiagolb** [comment]
Fixed in #208
