### ISSUE TITLE
Graph Connector initial version

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#33]

**Comment by fbeierle** [comment]
Currently, we are working on an example showing the inter-working of GraphConnector and Global Registry. For this, I need to send a message to the (Vertx) Msg Node, which will handle the message via
the GlobalRegistryConnector. So far, as an addressing scheme, `global://registry/`
is used (see https://github.com/reTHINK-project/dev-runtime-core/blob/dev-0.4/src/graphconnector/GraphConnector.js#L224).
This causes the RuntimeUA to look for a ProtoStub matching the domain "registry" and such a ProtoStub is not found.
How can I send a message to the Msg Node?

**Comment by pchainho** [comment]
The RuntimeRegistry.resolve() was updated to support `global://registry`. pls have a try

**Comment by fbeierle** [comment]
Thanks, it works now.

**Comment by pchainho** [comment]
What is the status of this one?

**Comment by fbeierle** [comment]
In runtime-core, all the necessary functions are included and tested. The branch is here: https://github.com/reTHINK-project/dev-runtime-core/tree/develop-graphConnector, I merged the latest changes of the develop branch.

As talked about in today's WP4 call, here, we provide a visualization of the message flow for the integration of the Graph Connector with the Global Registry:
https://github.com/reTHINK-project/dev-addressbook-app/wiki

@reTHINK-project/wp3 @reTHINK-project/wp4 

I will update this issue when the runtime-browser integration is finished.

**Comment by pchainho** [comment]
The Runtime Core Components like the Graph Connector shouldn't be reached by the App

I would recommend you to have this GUI as an admin GUI similar to Policy Engine and Id Module admin GUI

In this case it would be inside the core sandbox and it would have access to the core components API.

This [issue](https://github.com/reTHINK-project/dev-runtime-core/issues/63) was created for that

**Comment by fbeierle** [comment]
This is the way we have been implementing this since quite a while, see, e.g., the Pull Request from June: https://github.com/reTHINK-project/dev-runtime-browser/pull/52. The address book app is not just a simple Admin GUI, but an app we develop for WP5.

Furthermore, it seems like the right way to use the runtime-core to send messages to the MsgNode in order to query the Registries, see here: https://github.com/reTHINK-project/dev-discovery/issues/2#issuecomment-243621828.

**Comment by pchainho** [comment]
I was not aware of your design before. The runtime was designed a long time ago (pls see D3.1) fullfilling strong security requirements. Different types of components, notably core runtime components and protostubs, are executed in isolated sandboxes. Core Runtime components and protostubs, are only reached through the Message bus and message bus endpoints are only provided to components deployed and managed by the runtime itself. That's why Apps are not able to send messages to be routed through the MN. 

The admin GUI was conceived early this year to let the user safely manage its runtime core functionalities including the graph connector. I don't like the idea to let Apps write my graph and to be able to generate (delete?) my guid. 

One option, would be to have one lib to be imported by Hyperties to read the Graph Connector, then Hyperties could expose some API to Apps. This is something similar to the current discovery lib. We are also considering having these libs fully encapsulated by (Support) Hyperty eg a Disovery Hyperty.

But I would still keep writing access into the Runtime Admin GUI.

I think the effort is very limited and we would give you all the support needed

**Comment by fbeierle** [comment]
Thanks for your replay. I have a few questions:

What is the technical difference between an Admin GUI and an App? Aren't both HTML/JS that anyone can write? Or am I missing something?

What is a lib in the reTHINK context and how do they work? How would the lib be able to access the Runtime Core/Graph Connector?

**Comment by pchainho** [comment]
>What is the technical difference between an Admin GUI and an App? Aren't both HTML/JS that anyone can write? Or am I missing something?

The Admin GUI is inside the Core Runtime Sandbox (rethink iFrame) and have access to all core runtime components, while the App is outside and does not have access to any core runtime components. This means the Admin GUI is bundled with the Browser Runtime dist and only the Runtime Provider is able to designe/ implement it. Something similar to a Browser settings.

> What is a lib in the reTHINK context and how do they work? How would the lib be able to access the Runtime Core/Graph Connector?

Libs used by Hyperties are just normal javascript libs that can be imported by Hyperties. The only possible difference is that may need access to the msg bus (sandbox minibus) endpoint to send / receive messages. For example, the [discovery lib](https://github.com/reTHINK-project/dev-service-framework/blob/master/src/discovery/Discovery.js#L38) has the minibus passed in the constructor.

**Comment by pchainho** [comment]
What is the status of this one?

**Comment by fbeierle** [comment]
Everything used to work fine, but some changes somewhere (service framework? global registry?) led to another issue that we're currently working on: https://github.com/reTHINK-project/dev-runtime-browser/issues/62

@ishantiw @SenanSharhan @sgoendoer

**Comment by pchainho** [comment]
as clarified [here](https://github.com/reTHINK-project/dev-runtime-browser/issues/62#issuecomment-258919395) this issue should be solved having an Admin GUI for the Graph Connector and using the last version of the Toolkit for the development.

Could you update us on this pls?

**Comment by fbeierle** [comment]
The first version of the Address Book Admin GUI is available. To run it with the dev-hyperty-toolkit:

* Checkout dev-hyperty-toolkit, runtimes branch
* Change the version of runtime-brwoser in package.json in dev-hyperty-toolkit to:
    "runtime-browser": "github:rethink-project/dev-runtime-browser#develop-GraphConnector-Test",
* run "npm update"
* run "npm run start:browser"

There are some bugs introduced by changing from App to Admin GUI, that's why I didn't create new pull requests for runtime-core and runtime-browser yet.

**Comment by fbeierle** [comment]
Update: easier way to run it:
checkout branch "addressbook-app" from dev-hyperty-toolkit and run "npm run start:browser"

**Comment by fbeierle** [comment]
Update: We integrate the storage manager for the Graph Connector and also integrated the discovery service in the Address Book.

Pull requests for master branches in runtime-core and runtime-browser:
https://github.com/reTHINK-project/dev-runtime-core/pull/157
https://github.com/reTHINK-project/dev-runtime-browser/pull/72

To run (same as before):
checkout branch "addressbook-app" from dev-hyperty-toolkit and run "npm run start:browser"

**Comment by pchainho** [comment]
since I think this already merged I'm closing
