### ISSUE TITLE
RuntimeUA - Nodejs compatibility - Catalogue

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-runtime-core#54]
To make the runtime core compatible with nodejs, we need to do some changes at the code, namely, on:

- [runtime-catalogue (_makeExternalRequest)](https://github.com/reTHINK-project/dev-runtime-core/blob/dev-0.3/src/runtime/RuntimeCatalogue.js#L65)

Because the nodejs doesn't support browser dom attributes, like, window, XMLHttpResquest, and others;

I detected these ones, but if you know more open a new issue;

**Comment by Endebert** [comment]
I was just wondering how RuntimeFactory decides which implementation to use, since RuntimeFactory has no constructor arguments.
```
// one way...
var request = new Request(nodehttp, nodehttps);
var factory = new RuntimeFactory(request);

// or the other...
var factory = new RuntimeFactory(nodehttp, nodehttps);
```

**Comment by vitormsilva** [comment]
Hi @Endebert,

> I see, so the file itself will be replaced by a nodejs specific implementation during installation?

On this line [28](https://github.com/reTHINK-project/dev-runtime-core/blob/vsilva-factory/resources/RuntimeFactory.js#L28) of RuntimeFactory.js, for each implementation, you instantiate the respective Request (or other name). But the method makeRequest will always the same.

```javascript

  makeRequest() {
    let request = new Request();
    return request;
  }
```
(a small note, i will change the name makeRequest to createHttpRequest it's more logical);

> But even if there's only one Request class/file present, how does it get access to the http/https objects of nodejs, since they aren't globally available, or are they?

Inside the Request.js Class, you will implement the code specific for nodejs, and import the modules what you want.

```javascript
// Example of code implementation in nodejs;
var http = require('http');
var https = require('https');

class Request {
  constructor() {
  }
}
```

**Comment by Endebert** [comment]
ah ok I understand now, thanks for the explanation.

**Comment by Endebert** [comment]
Since the code has moved to dev-service-framework and I did the necessary code adaption, this can be closed.
