### ISSUE TITLE
RuntimeUA - Nodejs compatibility - Identity Module

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-runtime-core#55]
To make the runtime core compatible with nodejs, we need to do some changes at the code, namely, on:

 - [identityModule (login)](https://github.com/reTHINK-project/dev-runtime-core/blob/dev-0.3/src/identity/IdentityModule.js#L53)

Because the nodejs doesn't support browser dom attributes, like, window, XMLHttpResquest, and others;

I detected these ones, but if you know more open a new issue;

**Comment by pchainho** [comment]
We have agreed to move it to runtime browser
