### ISSUE TITLE
Runtime Registry:  persistence

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#58]
To use the generic "Persistence Manager" to persist registry data to enable the reusage of previously allocated and registered addresses

**Comment by pchainho** [comment]
What is the status of this one?

**Comment by gamdias** [comment]
No persistence yet

**Comment by pchainho** [comment]
Use Storage Manager, instead, as agreed [here](https://github.com/reTHINK-project/dev-runtime-core/issues/119)

**Comment by gamdias** [comment]
implemented the storage manager in runtime registry.
the changes can be seen in this branch: https://github.com/reTHINK-project/dev-runtime-core/tree/dev-address-reusage

if there is any problem with the implementation, please reopen the issue.
