### ISSUE TITLE
Identity Module: persistence

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#59]
To use the generic "Persistence Manager" to persist identity data avoiding the need to generate new tokens from IDPs that could be still valid

**Comment by pchainho** [comment]
What is the status of this one?

**Comment by gamdias** [comment]
No persistence yet

**Comment by pchainho** [comment]
Use Storage Manager, instead, as agreed [here](https://github.com/reTHINK-project/dev-runtime-core/issues/119)

**Comment by gamdias** [comment]
implemented the storage manager in identity module, that stores the registered identities.
the changes can be seen in this branch: https://github.com/reTHINK-project/dev-runtime-core/tree/dev-address-reusage

if there is any problem with the implementation, please reopen the issue.
