### ISSUE TITLE
IDP Proxy Stub

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#65]
This stub is to be used by the IDP Proxy to communicate with the Id Module through the Message BUS according to [this spec](https://github.com/reTHINK-project/dev-service-framework/blob/d3.2-working-docs/docs/specs/messages/identity-management-messages.md). It should be compliant with WebRTC Identity API

**Comment by gamdias** [comment]
The Identity Module is already using an IDPProxy. An IdpProxy that incorporates the protoStub. Later it should be separated.
