### ISSUE TITLE
Runtime Registration improvements for Phase 1

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#69]
Complete Runtime Registration according to [this spec](https://github.com/reTHINK-project/dev-service-framework/blob/d3.2-working-docs/docs/specs/messages/registration-messages.md), namely:

- Hyperty unregistration 
- Hyperty keep alive
- Hyperty search per Hyperty Type and User
- Data Objects Registration and Unregistration
- Data Object keep alive
- Data Object Search

@gamdias , @nunofmn  pls note there is a change in the resource path to reach hyperty instance registrations: `"/hyperty/user/<userURL>"`. This would allow to always use the RegistryDataObject  URL scheme in its resource path, having no difference between Hyperty Instances or Data Object instances registry entries. Let me know if you agree with this.

**Comment by gamdias** [comment]
Hyperty unregistration and Hyperty keep alive supported by the runtime Registry. (Hyperty keep alive is not yet supported by the msg-node connector)

**Comment by pchainho** [comment]
can we close this?

**Comment by gamdias** [comment]
Keep alive, the search methods, registration and unregistration of dataObject's implemented.
