### ISSUE TITLE
Registry getSandbox

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-runtime-core#71]
When i try to get a sandbox when various domains are registered, i always get "sandbox not found"

```javascript
getSandbox('hybroker.rethink.ptinovacao.pt') // Sandbox not found
```
![screenshot from 2016-03-04 18-02-44](https://cloud.githubusercontent.com/assets/10596749/13569149/34cc8036-e45e-11e5-892c-49105b0bed7c.png)

I think the:
 - hyperties always identified by: `hyperty://<domain>/<identifier>`
 - the stubs, always identified with something like: `msg-node.<domain>/<identifier>`

If you don't understand something i told, let me know.

**Comment by gamdias** [comment]
I've changed the method getSandbox() logic. If some problem persists, please tell me.

**Comment by gamdias** [comment]
The getSandbox() method got revised, it should be fine now.
