### ISSUE TITLE
Google auth redirect uri

### ISSUE THREAD

**Issue by dvilchez** [reTHINK-project/dev-runtime-core#73]
After Google authentication web-worker script URI is loaded in the popup and remains open.

You can check it in https://rethink.quobis.com
and in the attached image.
![screenshot from 2016-03-30 11-34-11](https://cloud.githubusercontent.com/assets/153025/14143491/da8e759e-f68b-11e5-84ce-e3bd5cba1b30.png)

**Comment by dvilchez** [comment]
To add more info. I had to mock IdentityModule on the standalone implementation because you can't open a popup in an android app.

**Comment by gamdias** [comment]
This problem should be resolved, once the DOM request is transferred to the runtime-Browser.

**Comment by pchainho** [comment]
As discussed today, the login window will be opened inside the core runtime sandbox i.e. the rethink iframe, and the Identity Module will ask the App Sandbox to unhide / hide the runtime core admin page that includes the login window. Messages to be handled by the App Sandbox are specified at:

https://github.com/reTHINK-project/dev-service-framework/blob/develop/docs/specs/messages/identity-management-messages.md#hide--unhide-identity-module-admin-page

**Comment by dvilchez** [comment]
Finally, we include a flag in the iframe declaration to enable close the popup
