### ISSUE TITLE
OrangeIdP - IdModule integration

### ISSUE THREAD

**Issue by KCorre** [reTHINK-project/dev-runtime-core#74]
@gamdias Just opening the issue so that we can discuss the integration.

There are currently two IdP hosted by Orange

**phpOIDC**
* hosted at https://oidc-ns.kermit.orange-labs.fr/
* doc at https://github.com/reTHINK-project/dev-IdPServer-phpOIDC

**oidc-node**
* hosted at https://energyq.idp.rethink.orange-labs.fr/
* doc at https://github.com/reTHINK-project/dev-IdPServer

Both services allow you to create user and clients. In that case you should only need user creation.

**Comment by KCorre** [comment]
*oidc-node* was tested on a small WebRTC application and seemed to work correctly, although Firefox did not provided any feedback. *phpOIDC* should be working too, but @sbecot went in holliday. I'm not sure that he conducted the test with success.

Note on pop-up. Sandboxed WebRTC proxy don't have right to open pop-up. They should return an error when a user is not logged-in (this error could contain a url for loggin, then used by the client application). See W3C specs for details. Thus, as our IdP Proxys are WebRTC compatible, they would work the same way.

**Comment by gamdias** [comment]
@KCorre I didn't had the chance to test it in a small isolated WebRTC application. Could you please send me that WebRTC application example, so I could test it? 
Thanks

**Comment by KCorre** [comment]
The repository for the webrtc app is [here](https://github.com/KCorre/webrtc_redirect_attack). It's a bit messy inside but 

* The homepage explains how to go to the webrtc app -> /webrtc
* The file to modify is located in /app/public/javascripts/webrtc.js

line 79 you have 	pc.setIdentityProvider("localhost:8080", "rethink-oidc");

Juste set the identity provider to another location (don't add https:// as it is added by firefox to force https). Debug info are scarce. Either you got an error and you get a message, or the authentication succeed. But in that case you get no message at all... A bit disapointing...

**Comment by pchainho** [comment]
What is the status of this one?

**Comment by gamdias** [comment]
There is still the problem with the cookies access.

**Comment by pchainho** [comment]
I understand this is done. reopen if needed
