### ISSUE TITLE
Runtime - RuntimeCatalogue dependency issue

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-runtime-core#75]
hi @dvilchez,

I would like to ask you an opinion related to a problem we are facing.
Inside the runtime-core, we have a runtime-catalogue dependency, but we don't know how to choose which use, the RuntimeCatalogue-Local or the RuntimeCatalogue, then, we have two possible solutions;

1. Generate two RuntimeUA distribution files, one with RuntimeCatalogue-Local and other with RuntimeCatalogue;
2. Pass into the runtimeFactory, side by side with the createSandbox, createAppSandbox and createHttpRequest, the runtimeCatalogue;

What do you think about this?

This is because we need to use on develop environment the RuntimeCatalogueLocal and on testbeds, we need to use the RuntimeCatalogue done by fokus;

All can contribute with ideas;

**Comment by dvilchez** [comment]
I think it is not a runtime-core problem rather than a runtime-browser problem. Runtime-browser needs to know which catalogue load in order to request runtime-core. Once runtime-browser resolve the right catalogue it can pass it to runtime-core.

The question is, how runtime-browser choose the right implementation? Maybe we can have two gulp task to generate rethink bundle one with dev dependencies and another one with production dependencies. 

How does it look to you?

**Comment by pchainho** [comment]
The selection of the Catalogue depends on your environment (development, production, test,..) that is agnostic of the runtime type.

**Comment by dvilchez** [comment]
ok, and how does runtime know which is your environment?

**Comment by pchainho** [comment]
with "npm start" you pass as parameter your environment

**Comment by dvilchez** [comment]
if npm start calls a gulp task you still can resolve the catalog through gulp tasks.

**Comment by pchainho** [comment]
yes, I think it is a gulp task that is then passing the right configuration to the runtime according to this parameter. @vitormsilva can provide you more details

**Comment by vitormsilva** [comment]
The problem is, the runtime-core is already bundle with one of the runtime-catalogue and is not possible to change after it bundled;

So, if you pass the runtimeCatalogue on runtimeFactory (2), there, you can still use the environment variables or gulp task to set which catalogue we can load from runtime-browser to inside the runtime-core.

I think this could be a better solution, because is more scalable (from side of runtime-core);

**Comment by vitormsilva** [comment]
Hi, 

I already was done the 2º point, mentioned when I create the issue. it's working in several places, like dev-service-framework and dev-hyperty-toolkit.

To handle with which catalogue (local or remote) you can choose, probably, you will need set the type of environment on dev-runtime-browser.

This is our suggestion. 
Something like:
```javascript
// https://github.com/reTHINK-project/dev-runtime-browser/blob/master/src/RuntimeUAStub.js
let RethinkBrowser = {
    env: function(obj) {
        // handle with obj
    }
    install: function(domain){
    }
}
```

From side of application you will have a configuration file, like [system.config.js](https://github.com/reTHINK-project/dev-hyperty-toolkit/blob/develop/system.config.json) on dev-hyperty-toolkit, but without the production and development, like this:

```json
{
   "env": "production",
   "domain" : "hybroker.rethink.ptinovacao.pt"
}
```
This file was generated through a task with the argument `--production`, for example;

If you have some doubts or suggestions you can say;
