### ISSUE TITLE
Receiving "Response timeout!" message after receiving correct response message

### ISSUE THREAD

**Issue by fbeierle** [reTHINK-project/dev-runtime-core#82]
We created a new branch to provide a demo for the Graph Connector (https://github.com/reTHINK-project/dev-runtime-core/tree/dev-0.5-GraphConnector).
Running the demo (https://github.com/reTHINK-project/dev-runtime-core/blob/dev-0.5-GraphConnector/example/demo.js), I get the following error when trying to send a message to the Global Registry:

![demo2](https://cloud.githubusercontent.com/assets/10813769/14742568/3f467b1c-089d-11e6-9131-b2b38fbe7869.png)

I am unsure why the IdentityModule is doing anything and what causes this error. Can anyone help?

**Comment by fbeierle** [comment]
After exchanging the ProtoStubs.json file with the one from dev-service-framework, I get a step further. I still get an error though, it now looks very similar to @Endebert 's issue (https://github.com/reTHINK-project/dev-runtime-browser/issues/40).

![demo3](https://cloud.githubusercontent.com/assets/10813769/14812706/9a880582-0b9e-11e6-9507-e7e41957b4f6.png)

**Comment by vitormsilva** [comment]
Hi @fbeierle,

You need to open the `https://msg-node.localhost:9090` on the browser to allow the certificate because this is not a valid certificate.

I hope this can solve your problem;

**Comment by fbeierle** [comment]
Thanks a lot for the help. Now it's working.

I will use this issue for my next question. After contacting the Global Registry and successfully receiving the expected reply message, I receive another message with "Response timeout!":

![demo4](https://cloud.githubusercontent.com/assets/10813769/14914707/f632cef6-0e0c-11e6-8bfb-cf028ce4c715.png)

So, everytime I message the Global Registry, I receive two messages: the expected answer and then a "Response timeout!" reply.

I am using a locally running vertx-msg-node. In the log output I see the correct reply. I'm guessing, the "Response timeout!" message is generated by the runtime. Is this a bug or did I use something incorrectly?

Full log: [demo4.txt](https://github.com/reTHINK-project/dev-runtime-core/files/242250/demo4.txt)

**Comment by pchainho** [comment]
can we close this one?

**Comment by fbeierle** [comment]
I don't know. Running the code now gives a different error earlier, I assume because of changes in dependencies.

**Comment by pchainho** [comment]
Logs pls?

**Comment by fbeierle** [comment]
![2016-06-08](https://cloud.githubusercontent.com/assets/10813769/15891059/0842e6c8-2d73-11e6-936b-af7bf91c361a.png)

**Comment by pchainho** [comment]
Can we close this one?

**Comment by fbeierle** [comment]
Please see the linked issue, the error still exists.

**Comment by fbeierle** [comment]
This is the message.body.value for the "Response timeout!" message (using commit https://github.com/reTHINK-project/dev-runtime-browser/commit/55373115ca2ca9124cd987866a0862b54097afb3, @ishantiw implemented a workaround for now).

![2016-09-19](https://cloud.githubusercontent.com/assets/10813769/18627282/774389dc-7e5a-11e6-8d22-2dcb0b1e532f.png)

**Comment by pchainho** [comment]
what was the work around?

Is this timeout still for the first read message or for a second read message?

**Comment by fbeierle** [comment]
> what was the work around?

Ignoring the "Response timeout!" message.

> Is this timeout still for the first read message or for a second read message?

There is only one read message. We get two replies for it.

**Comment by pchainho** [comment]
closing
