### ISSUE TITLE
Reusage of Hyperty and Data Object URLs

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#85]
There is a new requirement coming from the presence / context Hyperty: 

In order to improve performance and avoid performing the creation / subscription process everytime there is a new session, the data object URL persisted in the Domain Registry should be reused and allocated to the object

**Comment by NicoApizee** [comment]
Btw can we imagine that a context object, like presence or location, can be directly subscribe with a predictable hyperty url, with a pattern based on user guid for example ?

**Comment by pchainho** [comment]
yes, however this would require to change the current object address allocation process performed by the MN / Runtime Registry.

**Comment by pchainho** [comment]
Initial ideas to support this:

**`DataObjectReporter.close()`** 

* set `DataSyncObject.status = "disconnected"` *new field to be added*;
* ask sync manager to close DataObject *message to be specified*
* Sync Manager asks runtime registry to set `RegistryObject.status = "disconnected"`. *message to be specified*
* Sync Manager removes Reporter routing path (at runtime and msg bus level)

**`Syncher.open("objectURL")`**

**Comment by pchainho** [comment]
duplicated with https://github.com/reTHINK-project/specs/issues/6
