### ISSUE TITLE
Wrong parameter passed to registry.registerHyperty

### ISSUE THREAD

**Issue by dvilchez** [reTHINK-project/dev-runtime-core#86]
![bug](https://cloud.githubusercontent.com/assets/153025/15351036/48f9b576-1cdd-11e6-8be1-ed4eee627a13.jpg)

then the message sent to the registry domain contains a wrong hypertyDescriptorURL

<img width="530" alt="screen-shot-2016-05-18-09-48-54" src="https://cloud.githubusercontent.com/assets/153025/15351135/f1562eca-1cdd-11e6-8ec9-45091e422d5f.png">

**Comment by vitormsilva** [comment]
Seems to be fixed;
