### ISSUE TITLE
Add RuntimeUA.close() function and registry.unregisterAll()

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#89]

**Comment by pchainho** [comment]
@gamdias do you confirm `registry.unregisterAll()` is already available in develop branch?

**Comment by gamdias** [comment]
The method registry.unregisterAllHyperties() is implemented, but only unregister the registered Hyperties on the session.

If the method to unregister the DataObject is required, it can also be implemented. And then both methods can be called in a unregisterAll() method.

**Comment by pchainho** [comment]
Let's first have the unregisterAllHyperties(), now @vitormsilva should implement runtimaUA.close() to be used by browser runtime or nodejs runtime.

**Comment by vitormsilva** [comment]
Done.

The method close() will return a promise with true or false;
