### ISSUE TITLE
Uglify leads to error when calling generateGUID() in runtime-browser

### ISSUE THREAD

**Issue by fbeierle** [reTHINK-project/dev-runtime-core#91]
@dvilchez was right by suspecting the uglify process of the runtime-core to be the cause for the error we are getting when calling generateGUID() in the runtime-browser (see https://github.com/reTHINK-project/dev-runtime-browser/issues/48).

I used an non-uglified runtime in https://github.com/reTHINK-project/dev-runtime-browser/blob/develop-GraphConnector-Test/example/resources/descriptors/Runtimes.json and now it works.

Do we have an alternative to the uglify process?

**Comment by pchainho** [comment]
At this point the uglify process is required. We recommend you to fix your code to be compliant with uglify

**Comment by fbeierle** [comment]
Could you clarify which modules require the uglify process?

**Comment by pchainho** [comment]
uglify is mainly used to reduce the size of dists. At this point the develop branch is not uglified to facilitate development tests

**Comment by pchainho** [comment]
do you still have this problem?

**Comment by vitormsilva** [comment]
@fbeierle this problem presists? or can close the issue?

**Comment by ishantiw** [comment]
@vitormsilva I tested it from my end with uglified version of runtime_core and I can see that issue is still there. When I use non-uglified version of runtime-core then `generateGUID()` function works fine.

**Comment by pchainho** [comment]
can we close this one?

**Comment by fbeierle** [comment]
Somehow, uglification no longer seems to be an issue. I will close this for now.
