### ISSUE TITLE
Modifications On dev-runtime-core maybe needed for node

### ISSUE THREAD

**Issue by jboulmal** [reTHINK-project/dev-runtime-core#94]
We have added a slight modifications on `RuntimeUA.js`. We believe these modifications are needed for our developmenet of `#dev-runtime-nodejs`. Particularly in [RuntimeUA.js#L198](https://github.com/reTHINK-project/dev-runtime-core/blob/master/src/runtime/RuntimeUA.js#L198). 
We have added the following modifications:
` let dividedURL = divideURL(hypertyDescriptorURL);`
        `let identity = dividedURL.identity;`
       ` if (identity) {
          identity = identity.substring(identity.lastIndexOf('/') + 1);
        }`
      ` _hypertyDescriptor = JSON.parse(hypertyDescriptor);`
       ` let sourcePackageURL = _hypertyDescriptor[identity].sourcePackageURL;`
        `if (sourcePackageURL === '/sourcePackage') {`
          `return _hypertyDescriptor[identity].sourcePackage;
        }`

As seen form the above code snippet .  We have only parsed the `hypertyDescriptor`. Besides, we have used identity from the `hypertyDescriptorURL`  to identify a specific hyperty on the  `hypertyDescriptor`.

**Comment by vitormsilva** [comment]
why you need do that? the descriptor was identified by the hyperty url;

**Comment by jboulmal** [comment]
After modification done on service-framework, we no more need these modifications.
We believe we can close this issue.
Thanks

**Comment by NicoApizee** [comment]
Removing JSON.parse on hypertyDescriptor seem to resolv part of the problem.

In runtime-nodejs, we note that runtime dist file is not compatible, since it use the dist file generated generated from gulp dist task.
The behavior is the same by eval code from catalogue, or import source from node_module/.

What we note also is that when we manually transpile code from node_module/ src for runtime-core & service-framework, we can successfully load the runtime-core and go forward until loading hyperty process.

So I suppose that browserify process cannot be used for native node.

**Comment by jboulmal** [comment]
When we use  `_eval.apply(container, [sourcePackage.sourceCode]);`, we still get the issue described here : [RuntimeCatalogue.js not compatible with Nodejs Environment](https://github.com/reTHINK-project/dev-service-framework/issues/46) and here [Persistence Module not compatible with nodejs.](https://github.com/reTHINK-project/dev-runtime-core/issues/95). It seems that hyperties sourceCode is not compatible with Node.js

**Comment by jboulmal** [comment]
After update from @dvilchez and @vitormsilva, we still cannot load the runtime into nodejs.
 
[Package.json :](https://github.com/reTHINK-project/dev-runtime-nodejs/blob/nodejs-service-framework/package.json)
             ```runtime-core : develop```
              ``service-frmework: develop``

Here is our test procedure :
1- we run babel to `src/runtime/RuntimeUA.js`,
2- we browserify the result using option `--node`
3-we encode it into base-64
4- we load the Runtime
5-we evaluate the code in nodejs

Unfortunately, We get the following error message :
`error is  { evalmachine.<anonymous>:1`
`(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof `
`require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);
`var f=new Error("Cannot find module '"+o+"'");`
`throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};`
`t[o][0].call(l.exports,function(e){var n=t[o][1][e];`
return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){`
                                                                                                                                                                                           ^
Error: Cannot find module 'path'
at s (evalmachine.<anonymous>:1:148)
at evalmachine.<anonymous>:1:305
at Object.<anonymous> (evalmachine.<anonymous>:6942:10)
at Object.301.events (evalmachine.<anonymous>:7219:4)
at s (evalmachine.<anonymous>:1:254)
at evalmachine.<anonymous>:1:305
at evalmachine.<anonymous>:6814:24
at localStorage (evalmachine.<anonymous>:6801:5)
at Object.299../rem-localstorage (evalmachine.<anonymous>:6809:3)
at s (evalmachine.<anonymous>:1:254) code: 'MODULE_NOT_FOUND' }

**Comment by pchainho** [comment]
I guess we can close this. We'll reopen if needed

**Comment by jboulmal** [comment]
Ok
