### ISSUE TITLE
Howto handle identity management in runtime-nodejs

### ISSUE THREAD

**Issue by NicoApizee** [reTHINK-project/dev-runtime-core#96]
As the identification module is build in runtime-core, and call for window.open to start identification process with IDP, it does not seem possible to use it.
So how can we handle identification on nodejs runtime ?
Otherwise is it possible to start hyperty anonymously ?

**Comment by jmcrom** [comment]
see also https://github.com/reTHINK-project/governance-security-implementation/issues/49

**Comment by pchainho** [comment]
@NicoApizee the `window.open` should only be used in the browser-runtime extension not in the core-runtime: @gamdias can you confirm that?

One idea would be to have some mechanism to remotely manage Identity Tokens in the Identity Module, eg to expose some Identity Module API through a remote API.

**Comment by NicoApizee** [comment]
Why remotely ? It should be fine to be able to assert identity locally, on node (host identification, pkey...) as on browser side, this is a point that has already been discussed.

Btw the runtime-nodejs can also be used as standalone server, we can imagine hyperty to monitor resources/process for example, so does the identity is really mandatory ?

**Comment by pchainho** [comment]
Yes, but it should also be able to execute Hyperties from remote Users each one associated to different Identities

**Comment by NicoApizee** [comment]
It sound more like a forwarding identity for me (as a mail server that add header), but ok, I don't know all scenarios.

And what is the responsability of runtime-nodejs ? Does it should expose API to access the runtime-core instance in node, or literally a web server for remote access ?!

**Comment by jmcrom** [comment]
My 2 cents:

We must have a way to configure the identity __locally__ as a local assertion on the server (like @NicoApizee said)

We may need some remote API also (like @pchainho said), mostly for objects that have their idenity instantiated on a gateway (i.e. edge server)

Again let's begin with the obvious need and specify during phase 2 enhancements...

**Comment by gamdias** [comment]
> As the identification module is build in runtime-core, and call for window.open to start identification process with IDP, it does not seem possible to use it.
So how can we handle identification on nodejs runtime ?

For the nodejs as a temporary fix, the identity module checks if the `window` variable exists and if does not exist, it generates a random identity to be used by runtime registry. So it should work.

> Otherwise is it possible to start hyperty anonymously ?

For now, not yet. But will be possible soon.

**Comment by pchainho** [comment]
@NicoApizee did you manage to use the Id Module as explained above by @gamdias ?

**Comment by pchainho** [comment]
Just a preliminary solution. A more stable solution is needed. Keep it open

**Comment by pchainho** [comment]
As discussed [here](https://github.com/reTHINK-project/specs/issues/2#issue-175957412)

A more complete solution would be to use Browser Runtime admin GUI to manage identities in remote NodeJS servers. There would be the notion of runtime accounts where we could distinguish two roles: administrators and customers. Administrators manages customer accounts.

**Comment by pchainho** [comment]
duplicatet with https://github.com/reTHINK-project/specs/issues/17
