### ISSUE TITLE
Improve Runtime Logs

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-core#97]
Current Runtime logs are a mess and difficult to assist debugging.

We should agree on a common approach and analyse the usage of other methods or frameworks beside console.log():

http://www.hostingadvice.com/how-to/javascript-log-to-console/

**Comment by vitormsilva** [comment]
I found this tool, I don't know if someone uses, but looks like very interesting;

http://www.vorlonjs.com

**Comment by vitormsilva** [comment]
This issue is parcial resolved.

The source maps are activated in the  develop branch of runtime-core when the distribution file of Runtime.js was generated;

To generate it with sourcemaps 
```shell
gulp dist --development
```

**Comment by pchainho** [comment]
https://github.com/reTHINK-project/dev-runtime-browser/issues/53

**Comment by pchainho** [comment]
Logs have been Improved
